from __future__ import annotations

from typing import Any


def usage(
    purpose: str,
    input_: str,
    input_structure: str,
    input_rules: str,
    output: str,
    notes: str = "",
) -> dict[str, str]:
    return {
        "purpose": purpose,
        "input": input_,
        "input_structure": input_structure,
        "input_rules": input_rules,
        "output": output,
        "notes": notes,
    }


TOOLS: list[dict[str, Any]] = [
    {
        "id": "image_resize",
        "name": "图片降分辨率",
        "category": "图片视频",
        "description": "压缩或缩放指定文件夹内超过阈值的图片。",
        "usage": usage(
            "把超过大小阈值的图片按比例缩小并重新保存，用于批量降低图片体积和分辨率。",
            "输入一个包含图片的文件夹。",
            "默认只处理输入文件夹第一层图片；开启递归后会处理所有子文件夹中的图片。",
            "支持常见图片格式；文件大小超过阈值才会处理。输出留空时默认生成“原文件夹名_分辨率校正”。",
            "输出目录会保留相对目录结构；缩放后的图片写入输出目录，小图按策略移动或保留。",
        ),
        "risk": "medium",
        "entry": "tools.media_tools:resize_images",
        "supports_preview": True,
        "schema": [
            {"name": "input_dir", "label": "输入文件夹", "type": "path", "required": True},
            {"name": "output_dir", "label": "输出文件夹", "type": "path", "required": False},
            {"name": "size_threshold_mb", "label": "文件大小阈值 MB", "type": "number", "default": 9},
            {"name": "scale_factor", "label": "缩放比例", "type": "number", "default": 0.95},
            {"name": "quality", "label": "保存质量", "type": "number", "default": 98},
            {"name": "recursive", "label": "递归处理", "type": "boolean", "default": False},
        ],
    },
    {
        "id": "rename_and_classify",
        "name": "扁平化重命名与分类",
        "category": "图片视频",
        "description": "按序重命名并按媒体类型分类文件。",
        "usage": usage(
            "递归提取子目录文件，按序号加父目录名重命名，避免重名覆盖。",
            "输入一个待整理文件夹。",
            "可以包含多层子文件夹、图片、视频、GIF 和其他文件。",
            "文件会按当前排序递归处理；输出留空时在输入目录内整理，也可以指定独立输出目录。",
            "输出为扁平文件列表，文件名形如 00001_父目录_原文件名.ext。",
            "实际执行会移动文件，不是复制；预览模式只显示计划操作。",
        ),
        "risk": "medium",
        "entry": "tools.media_tools:rename_and_classify",
        "supports_preview": True,
        "schema": [
            {"name": "input_dir", "label": "输入文件夹", "type": "path", "required": True},
            {"name": "output_dir", "label": "输出文件夹", "type": "path", "required": False},
        ],
    },
    {
        "id": "split_video_gif",
        "name": "视频/GIF 分离",
        "category": "图片视频",
        "description": "将视频和 GIF 移动到独立子目录。",
        "usage": usage(
            "把视频文件和 GIF 从混合目录中分离出来，便于后续横竖屏分类或单独处理。",
            "输入一个包含媒体文件的文件夹。",
            "工具会递归扫描输入目录下的视频和 GIF。",
            "支持 mp4、mov、mkv、avi、webm、wmv、m4v、flv、rmvb、mpeg、mpg、3gp、mts、m2ts、ts、vob、ogv 等视频格式。",
            "视频移动到“视频”目录，GIF 移动到“视频/gif”目录；流程中会使用对应的命名输出目录。",
        ),
        "risk": "medium",
        "entry": "tools.media_tools:split_video_gif",
        "supports_preview": True,
        "schema": [{"name": "input_dir", "label": "输入文件夹", "type": "path", "required": True}],
    },
    {
        "id": "classify_landscape_images",
        "name": "图片横屏分类",
        "category": "图片视频",
        "description": "把横屏图片移动到横屏目录。",
        "usage": usage(
            "读取图片宽高，把横屏图片归入横屏目录，流程中也可同时分类竖屏。",
            "输入一个包含图片的文件夹。",
            "可以是已经扁平化的目录，也可以包含子目录。",
            "横屏判断为宽度大于等于高度；无法识别的图片会跳过并记录日志。",
            "横屏图片输出到“横屏”子目录；流程模式会配合分辨率校正目录生成“横屏/竖屏”结构。",
        ),
        "risk": "safe",
        "entry": "tools.media_tools:classify_landscape_images",
        "supports_preview": True,
        "schema": [{"name": "input_dir", "label": "输入文件夹", "type": "path", "required": True}],
    },
    {
        "id": "delete_small_videos",
        "name": "删除小视频文件",
        "category": "图片视频",
        "description": "按大小阈值清理小视频，遵循删除策略。",
        "usage": usage(
            "按文件大小筛选过小视频，用于清理无效片段或低价值视频文件。",
            "输入一个包含视频的文件夹。",
            "工具会递归扫描视频文件。",
            "必须勾选“启用删除”才会执行清理；未启用时只记录跳过。删除策略由设置页决定。",
            "符合阈值的视频会移动到 _trash 或永久删除；预览模式只列出候选文件。",
        ),
        "risk": "high",
        "entry": "tools.media_tools:delete_small_videos",
        "supports_preview": True,
        "schema": [
            {"name": "input_dir", "label": "输入文件夹", "type": "path", "required": True},
            {"name": "min_size_mb", "label": "最小大小 MB", "type": "number", "default": 1},
            {"name": "enable_delete", "label": "启用删除", "type": "boolean", "default": False},
        ],
    },
    {
        "id": "delete_low_resolution_videos",
        "name": "视频低分辨率筛选",
        "category": "图片视频",
        "description": "记录低分辨率视频候选项。",
        "usage": usage(
            "扫描视频宽高，记录可能低分辨率的视频候选项。",
            "输入一个包含视频的文件夹。",
            "工具会递归读取视频元数据，优先使用 ffprobe，失败时使用 OpenCV。",
            "当前工具只做记录和统计，不直接删除文件。",
            "输出为执行日志和候选统计，原文件不改变。",
        ),
        "risk": "medium",
        "entry": "tools.media_tools:delete_low_resolution_videos",
        "supports_preview": True,
        "schema": [{"name": "input_dir", "label": "输入文件夹", "type": "path", "required": True}],
    },
    {
        "id": "clean_txt_basic",
        "name": "TXT 基础清洗",
        "category": "文本小说",
        "description": "清理广告、乱码符号和重复空行。",
        "usage": usage(
            "清理 TXT 中的广告链接、推广行、零宽字符、重复行和多余空行。",
            "输入一个包含 TXT 文件的文件夹。",
            "默认处理第一层 TXT；开启递归后处理所有子文件夹 TXT。",
            "支持常见文本编码自动读取；强力清洗会额外移除较短的纯符号行。",
            "输出目录默认是“原文件夹名_清洗后”，并保留相对目录结构。",
        ),
        "risk": "safe",
        "entry": "tools.text_tools:clean_txt_basic",
        "supports_preview": True,
        "schema": [
            {"name": "input_dir", "label": "输入文件夹", "type": "path", "required": True},
            {"name": "output_dir", "label": "输出文件夹", "type": "path", "required": False},
            {"name": "recursive", "label": "递归处理", "type": "boolean", "default": False},
            {"name": "aggressive", "label": "强力清洗", "type": "boolean", "default": False},
        ],
    },
    {
        "id": "clean_txt_ai",
        "name": "AI 输入清洗",
        "category": "文本小说",
        "description": "使用基础清洗作为本地 AI 清洗前置处理。",
        "usage": usage(
            "用更强的基础规则整理 TXT，作为后续 AI 处理前的输入预清洗。",
            "输入一个包含 TXT 文件的文件夹。",
            "结构与 TXT 基础清洗一致。",
            "会启用强力清洗规则；适合去除明显噪声，但不调用外部 AI 服务。",
            "输出目录默认是“原文件夹名_清洗后”，文件以 UTF-8 写出。",
        ),
        "risk": "safe",
        "entry": "tools.text_tools:clean_txt_ai",
        "supports_preview": True,
        "schema": [
            {"name": "input_dir", "label": "输入文件夹", "type": "path", "required": True},
            {"name": "output_dir", "label": "输出文件夹", "type": "path", "required": False},
        ],
    },
    {
        "id": "split_txt_near_size",
        "name": "按目标字数切分",
        "category": "文本小说",
        "description": "按目标字数附近换行切分 TXT。",
        "usage": usage(
            "把单个 TXT 按目标字数切成多个片段，优先在目标字数附近的换行处断开。",
            "输入一个 TXT 文件。",
            "单文件输入，不读取文件夹。",
            "目标字数是理想片段长度；容差决定前后搜索换行的范围。",
            "输出目录默认是“文件名_chunks”，文件名为 原名_001.txt、原名_002.txt。",
        ),
        "risk": "safe",
        "entry": "tools.text_tools:split_txt_near_size",
        "supports_preview": True,
        "schema": [
            {"name": "input_file", "label": "输入 TXT", "type": "path", "required": True},
            {"name": "output_dir", "label": "输出文件夹", "type": "path", "required": False},
            {"name": "target_chars", "label": "目标字数", "type": "number", "default": 3300},
            {"name": "tolerance", "label": "容差", "type": "number", "default": 500},
        ],
    },
    {
        "id": "search_keyword",
        "name": "关键词搜索",
        "category": "文本小说",
        "description": "搜索 TXT 中关键词出现次数。",
        "usage": usage(
            "递归统计关键词在 TXT 文件中的出现次数，找出命中最多的文件。",
            "输入一个包含 TXT 的文件夹和一个关键词。",
            "工具固定递归扫描所有子文件夹 TXT。",
            "关键词为空会报错；搜索按大小写不敏感统计。",
            "输出为日志和命中列表，不修改原文件。",
        ),
        "risk": "safe",
        "entry": "tools.text_tools:search_keyword",
        "supports_preview": True,
        "schema": [
            {"name": "input_dir", "label": "输入文件夹", "type": "path", "required": True},
            {"name": "keyword", "label": "关键词", "type": "text", "required": True},
            {"name": "top_n", "label": "返回数量", "type": "number", "default": 10},
        ],
    },
    {
        "id": "replace_names",
        "name": "人物名替换",
        "category": "文本小说",
        "description": "按 old=>new 映射替换人物名。",
        "usage": usage(
            "按映射批量替换小说或文本中的人物名，并统计替换次数。",
            "输入一个 TXT 文件和替换映射。",
            "映射每行一个，格式为 old=>new，例如 张三=>李四。",
            "只处理单个文件；空映射或没有 old=>new 的行会报错。",
            "输出文件默认是“原文件名_replaced.txt”。",
        ),
        "risk": "safe",
        "entry": "tools.text_tools:replace_names",
        "supports_preview": True,
        "schema": [
            {"name": "input_file", "label": "输入 TXT", "type": "path", "required": True},
            {"name": "output_file", "label": "输出 TXT", "type": "path", "required": False},
            {"name": "mapping_text", "label": "替换映射", "type": "textarea", "required": True},
        ],
    },
    {
        "id": "split_novel_by_anchor",
        "name": "Anchor 章节切分",
        "category": "文本小说",
        "description": "按章节锚点文本切分小说。",
        "usage": usage(
            "按章节锚点把小说切成多个章节文件；锚点附近会优先找换行切分，其次找标点。",
            "输入一个 TXT 文件，可选填写章节锚点列表。",
            "锚点每行一个；不填写时会自动识别类似“第xx章/节/回”的行。",
            "搜索到锚点后会在窗口内选择更自然的切分点，优先换行，其次句号、问号、感叹号、分号等标点。",
            "输出目录默认是“文件名_chapters”，文件名为 chapter_001.txt、chapter_002.txt。",
        ),
        "risk": "safe",
        "entry": "tools.text_tools:split_novel_by_anchor",
        "supports_preview": True,
        "schema": [
            {"name": "input_file", "label": "输入 TXT", "type": "path", "required": True},
            {"name": "output_dir", "label": "输出文件夹", "type": "path", "required": False},
            {"name": "anchor_text", "label": "章节锚点", "type": "textarea", "required": False},
            {
                "name": "search_window_chars",
                "label": "锚点搜索窗口字符数",
                "type": "number",
                "default": 120,
                "advanced": True,
                "advanced_group": "章节切分",
            },
        ],
    },
    {
        "id": "group_files",
        "name": "按文件数量分组",
        "category": "文件管理",
        "description": "将文件按数量移动到 group_N 文件夹。",
        "usage": usage(
            "把一个目录中的文件按固定数量分组移动，便于分批上传或归档。",
            "输入一个文件夹。",
            "处理输入目录第一层文件，不处理子目录内文件。",
            "每组文件数必须大于 0；实际执行会移动文件。",
            "输出为 input_dir 内的 group_1、group_2 等分组目录。",
        ),
        "risk": "medium",
        "entry": "tools.file_tools:group_files",
        "supports_preview": True,
        "schema": [
            {"name": "input_dir", "label": "输入文件夹", "type": "path", "required": True},
            {"name": "files_per_group", "label": "每组文件数", "type": "number", "default": 80},
        ],
    },
    {
        "id": "split_large_folder",
        "name": "大文件夹分割",
        "category": "文件管理",
        "description": "按数量分割大文件夹。",
        "usage": usage(
            "把大文件夹按固定数量拆成多个 group_N 子目录。",
            "输入一个文件数量较多的文件夹。",
            "处理输入目录第一层文件。",
            "默认每 3000 个文件一组，可按需要调整。",
            "输出为 input_dir 内的 group_1、group_2 等目录。",
        ),
        "risk": "medium",
        "entry": "tools.file_tools:split_large_folder",
        "supports_preview": True,
        "schema": [
            {"name": "input_dir", "label": "输入文件夹", "type": "path", "required": True},
            {"name": "files_per_group", "label": "每组文件数", "type": "number", "default": 3000},
        ],
    },
    {
        "id": "sort_folders_by_size_rename",
        "name": "文件夹按大小排序重命名",
        "category": "文件管理",
        "description": "递归统计子文件夹大小后按 A-Z、a-z 前缀排序重命名。",
        "usage": usage(
            "整理输入目录下的子文件夹，按每个子文件夹递归总大小排序后加字母前缀。",
            "输入一个包含多个子文件夹的父目录。",
            "只重命名输入目录第一层子文件夹；每个子文件夹大小会包含其所有递归子文件。",
            "默认先还原已有 A_、B_ 这类前缀，再按大小从大到小重新命名；支持 A-Z、a-z 共 52 个排序前缀。",
            "输出仍在原父目录内，文件夹名形如 A_原文件夹名、B_原文件夹名。",
            "实际执行会重命名文件夹；建议先预览确认排序和目标名称。",
        ),
        "risk": "medium",
        "entry": "tools.file_tools:sort_folders_by_size_rename",
        "supports_preview": True,
        "schema": [
            {"name": "input_dir", "label": "输入文件夹", "type": "path", "required": True},
            {"name": "descending", "label": "按大小从大到小", "type": "boolean", "default": True},
            {"name": "restore_prefixes", "label": "先还原已有字母前缀", "type": "boolean", "default": True},
        ],
    },
    {
        "id": "filter_files_by_size",
        "name": "按文件大小筛选",
        "category": "文件管理",
        "description": "按大小复制或移动文件。",
        "usage": usage(
            "递归筛选达到大小阈值的文件，并把命中文件移动到输出目录。",
            "输入一个待筛选文件夹。",
            "可以包含多层子文件夹，工具会递归扫描所有文件。",
            "最小大小按 MB 计算；输出留空时默认生成“原文件夹名_筛选”。",
            "输出目录会保留输入下的相对路径结构。",
        ),
        "risk": "medium",
        "entry": "tools.file_tools:filter_files_by_size",
        "supports_preview": True,
        "schema": [
            {"name": "input_dir", "label": "输入文件夹", "type": "path", "required": True},
            {"name": "min_size_mb", "label": "最小大小 MB", "type": "number", "default": 0},
            {"name": "output_dir", "label": "输出文件夹", "type": "path", "required": False},
        ],
    },
    {
        "id": "batch_change_extension",
        "name": "批量修改后缀名",
        "category": "文件管理",
        "description": "批量把文件改为指定扩展名。",
        "usage": usage(
            "批量修改输入目录第一层文件扩展名。",
            "输入一个文件夹和目标后缀。",
            "只处理第一层文件，不递归子目录。",
            "后缀可填 .rar 或 rar；工具会自动补点。",
            "输出仍在原目录内，文件名主体不变，仅扩展名改变。",
        ),
        "risk": "medium",
        "entry": "tools.file_tools:batch_change_extension",
        "supports_preview": True,
        "schema": [
            {"name": "input_dir", "label": "输入文件夹", "type": "path", "required": True},
            {"name": "extension", "label": "目标后缀", "type": "text", "default": ".rar"},
        ],
    },
    {
        "id": "delete_empty_folders",
        "name": "删除空文件夹",
        "category": "文件管理",
        "description": "清理空文件夹，遵循删除策略。",
        "usage": usage(
            "递归查找并清理空文件夹，用于整理批处理后留下的空目录。",
            "输入一个文件夹。",
            "会从最深层目录开始扫描，避免父目录提前判断错误。",
            "必须勾选“启用删除”才会清理；删除策略由设置页决定。",
            "空目录会移动到 _trash 或永久删除；预览模式只列出候选目录。",
        ),
        "risk": "high",
        "entry": "tools.file_tools:delete_empty_folders",
        "supports_preview": True,
        "schema": [
            {"name": "input_dir", "label": "输入文件夹", "type": "path", "required": True},
            {"name": "enable_delete", "label": "启用删除", "type": "boolean", "default": False},
        ],
    },
]

FLOWS: list[dict[str, Any]] = [
    {
        "id": "media_clean_standard",
        "name": "图片视频整理标准流程",
        "category": "图片视频流程",
        "description": "重命名、分类、图片降分辨率、可选清理小文件。",
        "usage": usage(
            "组合执行递归重命名、视频/GIF 分离、横竖屏分类、图片降分辨率和可选小视频清理。",
            "输入一个媒体文件夹；批量模式下输入为父目录，父目录内每个子文件夹作为一个子任务。",
            "单任务示例：输入 xx；批量示例：输入目录内包含 xx、aa 两个子目录。",
            "输出留空时自动按输入父目录生成。批量时每个子任务使用自己的目录名生成输出。",
            "输出示例：xx_分辨率校正/横屏、xx_分辨率校正/竖屏、xx_视频/横屏、xx_视频/竖屏；批量时还会生成 aa 对应目录。",
            "实际执行会大量移动文件；建议先用预览确认。",
        ),
        "risk": "high",
        "entry": "pipelines.media_clean_pipeline:run",
        "supports_preview": True,
        "steps": ["递归重命名", "视频/GIF 分离", "视频横竖屏分类", "图片横竖屏分类", "图片降分辨率", "清理小视频文件"],
        "schema": [
            {"name": "input_dir", "label": "输入文件夹", "type": "path", "required": True},
            {"name": "output_dir", "label": "输出文件夹", "type": "path", "required": False},
            {"name": "batch_subfolders", "label": "批量处理子文件夹", "type": "boolean", "default": False},
            {"name": "enable_resize", "label": "启用图片降分辨率", "type": "boolean", "default": True},
            {"name": "enable_delete", "label": "启用删除类步骤", "type": "boolean", "default": False},
            {
                "name": "size_threshold_mb",
                "label": "图片降分辨率：文件大小阈值 MB",
                "type": "number",
                "default": 9,
                "advanced": True,
                "advanced_group": "图片降分辨率",
            },
            {
                "name": "scale_factor",
                "label": "图片降分辨率：缩放比例",
                "type": "number",
                "default": 0.95,
                "advanced": True,
                "advanced_group": "图片降分辨率",
            },
            {
                "name": "quality",
                "label": "图片降分辨率：保存质量",
                "type": "number",
                "default": 98,
                "advanced": True,
                "advanced_group": "图片降分辨率",
            },
            {
                "name": "min_size_mb",
                "label": "删除小视频：最小大小 MB",
                "type": "number",
                "default": 1,
                "advanced": True,
                "advanced_group": "删除类步骤",
            },
        ],
    },
    {
        "id": "txt_clean_split",
        "name": "TXT 清洗 + 3300 字切分流程",
        "category": "文本小说流程",
        "description": "清洗 TXT 后按目标字数切分。",
        "usage": usage(
            "先清洗 TXT，再按目标字数切分，适合把小说整理成固定长度片段。",
            "输入一个包含 TXT 的文件夹。",
            "默认处理第一层 TXT；开启递归后保留相对目录结构处理子目录 TXT。",
            "清洗模式可选基础清洗或 AI 前置清洗；目标字数和容差控制切分长度。",
            "输出目录默认是“原文件夹名_clean_split”，内部包含清洗和切分结果。",
        ),
        "risk": "safe",
        "entry": "pipelines.txt_clean_split_pipeline:run",
        "supports_preview": True,
        "steps": ["TXT 清洗", "按目标字数切分", "生成日志"],
        "schema": [
            {"name": "input_dir", "label": "输入文件夹", "type": "path", "required": True},
            {"name": "output_dir", "label": "输出文件夹", "type": "path", "required": False},
            {"name": "clean_mode", "label": "清洗模式", "type": "select", "default": "basic", "options": ["basic", "ai"]},
            {"name": "target_chars", "label": "目标字数", "type": "number", "default": 3300},
            {"name": "tolerance", "label": "容差", "type": "number", "default": 500},
            {"name": "recursive", "label": "递归处理", "type": "boolean", "default": False},
        ],
    },
    {
        "id": "name_replace",
        "name": "小说人物名替换流程",
        "category": "文本小说流程",
        "description": "按映射替换小说人物名并输出报告。",
        "usage": usage(
            "按映射替换单本小说中的人物名，并输出替换统计。",
            "输入一个 TXT 文件和替换映射。",
            "映射每行一个，格式为 old=>new。",
            "适合改名、统一译名或替换角色称呼。",
            "输出 TXT 默认是“原文件名_replaced.txt”，日志中包含每个旧名的替换次数。",
        ),
        "risk": "safe",
        "entry": "pipelines.name_replace_pipeline:run",
        "supports_preview": True,
        "steps": ["读取 TXT", "解析映射", "替换人物名", "输出报告"],
        "schema": [
            {"name": "input_file", "label": "输入 TXT", "type": "path", "required": True},
            {"name": "output_file", "label": "输出 TXT", "type": "path", "required": False},
            {"name": "mapping_text", "label": "替换映射", "type": "textarea", "required": True},
        ],
    },
    {
        "id": "folder_group",
        "name": "文件夹按数量分组流程",
        "category": "文件整理流程",
        "description": "将文件夹内文件按固定数量分组。",
        "usage": usage(
            "把文件夹第一层文件按固定数量移动到多个分组目录。",
            "输入一个文件夹。",
            "不递归处理子目录内文件。",
            "每组文件数决定 group_N 的容量，适合把大量文件分批。",
            "输出为输入目录内的 group_1、group_2 等目录。",
        ),
        "risk": "medium",
        "entry": "pipelines.folder_group_pipeline:run",
        "supports_preview": True,
        "steps": ["读取文件夹", "创建 group_N", "移动文件", "输出统计"],
        "schema": [
            {"name": "input_dir", "label": "输入文件夹", "type": "path", "required": True},
            {"name": "files_per_group", "label": "每组文件数", "type": "number", "default": 80},
        ],
    },
]


def _without_entry(item: dict[str, Any]) -> dict[str, Any]:
    return dict(item)


def list_tools() -> list[dict[str, Any]]:
    return [_without_entry(tool) for tool in TOOLS]


def list_flows() -> list[dict[str, Any]]:
    return [_without_entry(flow) for flow in FLOWS]


def get_tool(tool_id: str) -> dict[str, Any] | None:
    return next((tool for tool in TOOLS if tool["id"] == tool_id), None)


def get_flow(flow_id: str) -> dict[str, Any] | None:
    return next((flow for flow in FLOWS if flow["id"] == flow_id), None)
